CREATE TABLE IF NOT EXISTS USERS
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	PHONE_NUMBER VARCHAR(15) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE USERS
MODIFY COLUMN PASSWORD VARCHAR(255) NOT NULL;

CREATE TABLE IF NOT EXISTS products
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	product_name VARCHAR(100) NOT NULL,
	description VARCHAR(500) NOT NULL,
	category VARCHAR(100) NOT NULL,
	price DECIMAL(10,2) NOT NULL,
	quantity INT NOT NULL
);