CREATE TABLE IF NOT EXISTS USERS
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	PHONE_NUMBER VARCHAR(15) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);